# Global quarkus settings
quarkus.banner.enabled=false
quarkus.analytics.disabled=true

# Explicit log format (default includes thread)
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %c{2.} - %s%e%n

# Disable logging below warning level for logger "io.quarkus"
quarkus.log.category."io.quarkus".level=WARN

quarkus.package.output-name=needle
quarkus.package.jar.add-runner-suffix=false
